linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - unused
    - staticcheck
issues: 
  exclude-use-default: false 
