linters:
  enable:
    - dogsled
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - unused
    - staticcheck
    - typecheck
    - usestdlibvars
    - exportloopref
issues: 
  exclude-use-default: false