// Code generated by mockery v2.40.1. DO NOT EDIT.

package githubclient

import (
	githubclient "github.com/chelnak/gh-changelog/internal/githubclient"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockGitHubClient is an autogenerated mock type for the GitHubClient type
type MockGitHubClient struct {
	mock.Mock
}

type MockGitHubClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitHubClient) EXPECT() *MockGitHubClient_Expecter {
	return &MockGitHubClient_Expecter{mock: &_m.Mock}
}

// GetPullRequestsBetweenDates provides a mock function with given fields: from, to
func (_m *MockGitHubClient) GetPullRequestsBetweenDates(from time.Time, to time.Time) ([]githubclient.PullRequest, error) {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestsBetweenDates")
	}

	var r0 []githubclient.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]githubclient.PullRequest, error)); ok {
		return rf(from, to)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []githubclient.PullRequest); ok {
		r0 = rf(from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]githubclient.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubClient_GetPullRequestsBetweenDates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestsBetweenDates'
type MockGitHubClient_GetPullRequestsBetweenDates_Call struct {
	*mock.Call
}

// GetPullRequestsBetweenDates is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
func (_e *MockGitHubClient_Expecter) GetPullRequestsBetweenDates(from interface{}, to interface{}) *MockGitHubClient_GetPullRequestsBetweenDates_Call {
	return &MockGitHubClient_GetPullRequestsBetweenDates_Call{Call: _e.mock.On("GetPullRequestsBetweenDates", from, to)}
}

func (_c *MockGitHubClient_GetPullRequestsBetweenDates_Call) Run(run func(from time.Time, to time.Time)) *MockGitHubClient_GetPullRequestsBetweenDates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockGitHubClient_GetPullRequestsBetweenDates_Call) Return(_a0 []githubclient.PullRequest, _a1 error) *MockGitHubClient_GetPullRequestsBetweenDates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubClient_GetPullRequestsBetweenDates_Call) RunAndReturn(run func(time.Time, time.Time) ([]githubclient.PullRequest, error)) *MockGitHubClient_GetPullRequestsBetweenDates_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoName provides a mock function with given fields:
func (_m *MockGitHubClient) GetRepoName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepoName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitHubClient_GetRepoName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoName'
type MockGitHubClient_GetRepoName_Call struct {
	*mock.Call
}

// GetRepoName is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) GetRepoName() *MockGitHubClient_GetRepoName_Call {
	return &MockGitHubClient_GetRepoName_Call{Call: _e.mock.On("GetRepoName")}
}

func (_c *MockGitHubClient_GetRepoName_Call) Run(run func()) *MockGitHubClient_GetRepoName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_GetRepoName_Call) Return(_a0 string) *MockGitHubClient_GetRepoName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubClient_GetRepoName_Call) RunAndReturn(run func() string) *MockGitHubClient_GetRepoName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoOwner provides a mock function with given fields:
func (_m *MockGitHubClient) GetRepoOwner() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepoOwner")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockGitHubClient_GetRepoOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoOwner'
type MockGitHubClient_GetRepoOwner_Call struct {
	*mock.Call
}

// GetRepoOwner is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) GetRepoOwner() *MockGitHubClient_GetRepoOwner_Call {
	return &MockGitHubClient_GetRepoOwner_Call{Call: _e.mock.On("GetRepoOwner")}
}

func (_c *MockGitHubClient_GetRepoOwner_Call) Run(run func()) *MockGitHubClient_GetRepoOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_GetRepoOwner_Call) Return(_a0 string) *MockGitHubClient_GetRepoOwner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGitHubClient_GetRepoOwner_Call) RunAndReturn(run func() string) *MockGitHubClient_GetRepoOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function with given fields:
func (_m *MockGitHubClient) GetTags() ([]githubclient.Tag, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 []githubclient.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]githubclient.Tag, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []githubclient.Tag); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]githubclient.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitHubClient_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type MockGitHubClient_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) GetTags() *MockGitHubClient_GetTags_Call {
	return &MockGitHubClient_GetTags_Call{Call: _e.mock.On("GetTags")}
}

func (_c *MockGitHubClient_GetTags_Call) Run(run func()) *MockGitHubClient_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_GetTags_Call) Return(_a0 []githubclient.Tag, _a1 error) *MockGitHubClient_GetTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitHubClient_GetTags_Call) RunAndReturn(run func() ([]githubclient.Tag, error)) *MockGitHubClient_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitHubClient creates a new instance of MockGitHubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitHubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitHubClient {
	mock := &MockGitHubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
