// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GitClient is an autogenerated mock type for the GitClient type
type GitClient struct {
	mock.Mock
}

// GetDateOfHash provides a mock function with given fields: hash
func (_m *GitClient) GetDateOfHash(hash string) (time.Time, error) {
	ret := _m.Called(hash)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFirstCommit provides a mock function with given fields:
func (_m *GitClient) GetFirstCommit() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGitClient creates a new instance of GitClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewGitClient(t testing.TB) *GitClient {
	mock := &GitClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
