// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	changelog "github.com/chelnak/gh-changelog/pkg/changelog"
	mock "github.com/stretchr/testify/mock"
)

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// Parse provides a mock function with given fields:
func (_m *Parser) Parse() (changelog.Changelog, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 changelog.Changelog
	var r1 error
	if rf, ok := ret.Get(0).(func() (changelog.Changelog, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() changelog.Changelog); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(changelog.Changelog)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewParser creates a new instance of Parser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Parser {
	mock := &Parser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
