# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: "write"

env:
  GO_VERSION: 1.21

jobs:
  release:
    name: "release"
    runs-on: "ubuntu-latest"
    env:
      WORKINGDIR: ${{ github.workspace }}
    steps:

      - name: "checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "setup go"
        uses: "actions/setup-go@v2"
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: "release"
        uses: "goreleaser/goreleaser-action@v2"
        with:
          version: "latest"
          args: "release --rm-dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
